In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
tf.__version__

'2.1.0'

In [2]:
import pandas as pd
df = pd.read_csv('./dataset/iris.csv', 
                 names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"])
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
dataset = df.values
X = dataset[:,0:4].astype(float)
Y_obj = dataset[:,4]
Y_obj[0], Y_obj[50], Y_obj[100]

('Iris-setosa', 'Iris-versicolor', 'Iris-virginica')

In [24]:
Y_obj.shape

(150,)

In [5]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [6]:
from sklearn.preprocessing import LabelEncoder

e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

In [7]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
# One hot encoding
Y_encoded = tf.keras.utils.to_categorical(Y)
Y_encoded[0], Y_encoded[50], Y_encoded[100]

(array([1., 0., 0.], dtype=float32),
 array([0., 1., 0.], dtype=float32),
 array([0., 0., 1.], dtype=float32))

In [9]:
Y_encoded.shape

(150, 3)

In [10]:
# seed 값 설정
seed = 0
tf.random.set_seed(seed)

In [11]:
# 딥러닝 모델 설정
model = Sequential([
    Dense(16, input_shape=(4,), activation='relu'),
    Dense(3, activation='softmax')
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                80        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 51        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [12]:
# 모델 컴파일 
model.compile(loss='categorical_crossentropy', 
              optimizer='adam',
              metrics=['accuracy'])

In [27]:
#X.shape
Y_encoded.shape

(150, 3)

In [13]:
# 모델 실행
model.fit(X, Y_encoded, epochs=50, batch_size=10)

Train on 150 samples
Epoch 1/50
150/150 [==============================] - 0s 2ms/sample - loss: 2.4639 - accuracy: 0.3333
Epoch 2/50
150/150 [==============================] - 0s 80us/sample - loss: 2.0513 - accuracy: 0.3333
Epoch 3/50
150/150 [==============================] - 0s 80us/sample - loss: 1.6216 - accuracy: 0.4533
Epoch 4/50
150/150 [==============================] - 0s 91us/sample - loss: 1.2453 - accuracy: 0.6400
Epoch 5/50
150/150 [==============================] - 0s 79us/sample - loss: 0.9448 - accuracy: 0.6667
Epoch 6/50
150/150 [==============================] - 0s 80us/sample - loss: 0.7664 - accuracy: 0.6667
Epoch 7/50
150/150 [==============================] - 0s 91us/sample - loss: 0.7010 - accuracy: 0.6933
Epoch 8/50
150/150 [==============================] - 0s 86us/sample - loss: 0.6672 - accuracy: 0.7467
Epoch 9/50
150/150 [==============================] - 0s 82us/sample - loss: 0.6445 - accuracy: 0.7200
Epoch 10/50
150/150 [==============================] 

In [14]:
# 결과 출력 
print("\n Accuracy: %.4f" % (model.evaluate(X, Y_encoded, verbose=2)[1]))

150/150 - 0s - loss: 0.2989 - accuracy: 0.9800

 Accuracy: 0.9800


In [15]:
# 딥러닝 모델 설정
model2 = Sequential([
    Dense(12, input_shape=(4,), activation='relu'),
    Dense(8, activation='relu'),
    Dense(3, activation='softmax')
])
model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 12)                60        
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 27        
Total params: 191
Trainable params: 191
Non-trainable params: 0
_________________________________________________________________


In [16]:
# 모델 컴파일 
model2.compile(loss='categorical_crossentropy', 
              optimizer='adam',
              metrics=['accuracy'])

In [17]:
# 모델 실행
model2.fit(X, Y_encoded, epochs=500, batch_size=30)

Train on 150 samples
Epoch 1/500
150/150 [==============================] - 0s 2ms/sample - loss: 1.5376 - accuracy: 0.3333
Epoch 2/500
150/150 [==============================] - 0s 47us/sample - loss: 1.2429 - accuracy: 0.3333
Epoch 3/500
150/150 [==============================] - 0s 46us/sample - loss: 1.0258 - accuracy: 0.3400
Epoch 4/500
150/150 [==============================] - 0s 33us/sample - loss: 0.8710 - accuracy: 0.5400
Epoch 5/500
150/150 [==============================] - 0s 40us/sample - loss: 0.7780 - accuracy: 0.6533
Epoch 6/500
150/150 [==============================] - 0s 33us/sample - loss: 0.7237 - accuracy: 0.6667
Epoch 7/500
150/150 [==============================] - 0s 40us/sample - loss: 0.6909 - accuracy: 0.7867
Epoch 8/500
150/150 [==============================] - 0s 40us/sample - loss: 0.6735 - accuracy: 0.8800
Epoch 9/500
150/150 [==============================] - 0s 33us/sample - loss: 0.6570 - accuracy: 0.8133
Epoch 10/500
150/150 [======================

150/150 [==============================] - 0s 40us/sample - loss: 0.1077 - accuracy: 0.9800
Epoch 156/500
150/150 [==============================] - 0s 40us/sample - loss: 0.1080 - accuracy: 0.9800
Epoch 157/500
150/150 [==============================] - 0s 33us/sample - loss: 0.1068 - accuracy: 0.9800
Epoch 158/500
150/150 [==============================] - 0s 40us/sample - loss: 0.1051 - accuracy: 0.9800
Epoch 159/500
150/150 [==============================] - 0s 40us/sample - loss: 0.1054 - accuracy: 0.9800
Epoch 160/500
150/150 [==============================] - 0s 46us/sample - loss: 0.1048 - accuracy: 0.9800
Epoch 161/500
150/150 [==============================] - 0s 36us/sample - loss: 0.1032 - accuracy: 0.9800
Epoch 162/500
150/150 [==============================] - 0s 33us/sample - loss: 0.1075 - accuracy: 0.9800
Epoch 163/500
150/150 [==============================] - 0s 41us/sample - loss: 0.1062 - accuracy: 0.9733
Epoch 164/500
150/150 [==============================] - 0s 

150/150 [==============================] - 0s 47us/sample - loss: 0.0682 - accuracy: 0.9800
Epoch 310/500
150/150 [==============================] - 0s 40us/sample - loss: 0.0678 - accuracy: 0.9733
Epoch 311/500
150/150 [==============================] - 0s 33us/sample - loss: 0.0683 - accuracy: 0.9867
Epoch 312/500
150/150 [==============================] - 0s 40us/sample - loss: 0.0675 - accuracy: 0.9867
Epoch 313/500
150/150 [==============================] - 0s 33us/sample - loss: 0.0662 - accuracy: 0.9867
Epoch 314/500
150/150 [==============================] - 0s 46us/sample - loss: 0.0671 - accuracy: 0.9867
Epoch 315/500
150/150 [==============================] - 0s 33us/sample - loss: 0.0663 - accuracy: 0.9867
Epoch 316/500
150/150 [==============================] - 0s 46us/sample - loss: 0.0672 - accuracy: 0.9800
Epoch 317/500
150/150 [==============================] - 0s 33us/sample - loss: 0.0660 - accuracy: 0.9867
Epoch 318/500
150/150 [==============================] - 0s 

150/150 [==============================] - 0s 33us/sample - loss: 0.0577 - accuracy: 0.9800
Epoch 464/500
150/150 [==============================] - 0s 33us/sample - loss: 0.0580 - accuracy: 0.9733
Epoch 465/500
150/150 [==============================] - 0s 33us/sample - loss: 0.0585 - accuracy: 0.9800
Epoch 466/500
150/150 [==============================] - 0s 37us/sample - loss: 0.0606 - accuracy: 0.9733
Epoch 467/500
150/150 [==============================] - 0s 40us/sample - loss: 0.0575 - accuracy: 0.9867
Epoch 468/500
150/150 [==============================] - 0s 33us/sample - loss: 0.0572 - accuracy: 0.9867
Epoch 469/500
150/150 [==============================] - 0s 33us/sample - loss: 0.0574 - accuracy: 0.9733
Epoch 470/500
150/150 [==============================] - 0s 40us/sample - loss: 0.0578 - accuracy: 0.9800
Epoch 471/500
150/150 [==============================] - 0s 38us/sample - loss: 0.0574 - accuracy: 0.9800
Epoch 472/500
150/150 [==============================] - 0s 

In [18]:
# 결과 출력 
print("\n Accuracy: %.4f" % (model2.evaluate(X, Y_encoded, verbose=2)[1]))

150/150 - 0s - loss: 0.0559 - accuracy: 0.9800

 Accuracy: 0.9800
