# 21번 파일 

In [1]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [12]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 2020
np.random.seed(seed)
tf.set_random_seed(seed)

In [14]:

# x, y의 데이터 값
x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]]) 
y_data = np.array([0, 1, 1, 0]).reshape(-1,1)
print(x_data.shape, y_data.shape)
y_data

(4, 2) (4, 1)


array([[0],
       [1],
       [1],
       [0]])

In [15]:
y_data = y_data.reshape(4,1)
print(x_data.shape, y_data.shape)
y_data

(4, 2) (4, 1)


array([[0],
       [1],
       [1],
       [0]])

In [16]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [17]:
# Layer 1
W1 = tf.Variable(tf.random_normal([2, 2]), dtype=tf.float32)
b1 = tf.Variable(tf.random_normal([2]), dtype=tf.float32)
L1 = tf.sigmoid(tf.matmul(X, W1) + b1)

In [18]:
# Layer 2
W2 = tf.Variable(tf.random_normal([2, 1]), dtype=tf.float32)
b2 = tf.Variable(tf.random_normal([1]), dtype=tf.float32)
hypo = tf.sigmoid(tf.matmul(L1, W2) + b2)

In [8]:
# Cost - Binary Cross Entropy
cost = -tf.reduce_mean(Y * tf.log(hypo) + (1.-Y) * tf.log(1.-hypo))

In [9]:
# Optimizer - Adam
lr = 0.1
train = tf.train.AdamOptimizer(learning_rate=lr).minimize(cost)

In [10]:
# Accuracy 계산
predicted = tf.cast(hypo > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [11]:
# 학습
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)
            
    # Accuracy report
    h, p, a = sess.run([hypo, predicted, accuracy], feed_dict={X: x_data, Y: y_data}) 
    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")
    
    # Weight, bias
    W1_, b1_, W2_, b2_ = sess.run([W1, b1, W2, b2])
    print(f"\nW1:\n{W1_} \nb1:\n{b1_} \nW2:\n{W2_}\nb1:\n{b2_}")

0 0.7533897
1000 0.47749627
2000 0.006484731
3000 0.0001510994
4000 5.9935097e-05
5000 2.9862582e-05
6000 1.6302065e-05
7000 9.283487e-06
8000 5.4389457e-06
9000 3.2037572e-06
10000 1.9222525e-06

Hypothesis:
[[7.8669706e-07]
 [9.9999857e-01]
 [9.9999869e-01]
 [4.1864205e-06]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

W1:
[[-13.626901  -8.043681]
 [-13.894696  -8.069943]] 
b1:
[ 5.674629 11.658168] 
W2:
[[-28.375456]
 [ 26.915918]]
b1:
[-12.692699]
