In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.


In [2]:
# seed 값 설정
seed = 2020
np.random.seed(seed)
tf.random.set_seed(seed)

In [7]:
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '../dataset/hard_handwriting_shape/train',
        target_size=(24, 24),
        batch_size=3,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '../dataset/hard_handwriting_shape/test',
        target_size=(24, 24),    
        batch_size=3,
        class_mode='categorical')

Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.


In [8]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu', input_shape=(24,24,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 22, 22, 32)        896       
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 20, 20, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 10, 10, 64)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 6400)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               819328    
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 387       
Total params: 839,107
Trainable params: 839,107
Non-trainable params: 0
________________________________________________

In [9]:

model.compile(loss='categorical_crossentropy', 
              optimizer='adam', metrics=['accuracy'])

In [10]:
model.fit_generator(
        train_generator,
        steps_per_epoch=15,
        epochs=200,
        validation_data=test_generator,
        validation_steps=5)

Epoch 1/200
15/15 [==============================] - 0s 19ms/step - loss: 1.0254 - accuracy: 0.5778 - val_loss: 1.7327 - val_accuracy: 0.3333
Epoch 2/200
15/15 [==============================] - 0s 10ms/step - loss: 0.2136 - accuracy: 0.9778 - val_loss: 0.8492 - val_accuracy: 0.3333
Epoch 3/200
15/15 [==============================] - 0s 10ms/step - loss: 0.0210 - accuracy: 1.0000 - val_loss: 4.2971 - val_accuracy: 0.3333
Epoch 4/200
15/15 [==============================] - 0s 10ms/step - loss: 0.0028 - accuracy: 1.0000 - val_loss: 5.0991 - val_accuracy: 0.3333
Epoch 5/200
15/15 [==============================] - 0s 10ms/step - loss: 4.3123e-04 - accuracy: 1.0000 - val_loss: 6.6496 - val_accuracy: 0.3333
Epoch 6/200
15/15 [==============================] - 0s 10ms/step - loss: 2.7374e-04 - accuracy: 1.0000 - val_loss: 2.3125 - val_accuracy: 0.3333
Epoch 7/200
15/15 [==============================] - 0s 11ms/step - loss: 1.6778e-04 - accuracy: 1.0000 - val_loss: 5.3675 - val_accuracy: 0

Epoch 57/200
15/15 [==============================] - 0s 16ms/step - loss: 2.9882e-06 - accuracy: 1.0000 - val_loss: 11.1454 - val_accuracy: 0.3333
Epoch 58/200
15/15 [==============================] - 0s 10ms/step - loss: 2.8425e-06 - accuracy: 1.0000 - val_loss: 0.3403 - val_accuracy: 0.3333
Epoch 59/200
15/15 [==============================] - 0s 10ms/step - loss: 2.7683e-06 - accuracy: 1.0000 - val_loss: 8.8917 - val_accuracy: 0.3333
Epoch 60/200
15/15 [==============================] - 0s 11ms/step - loss: 2.6544e-06 - accuracy: 1.0000 - val_loss: 3.0446 - val_accuracy: 0.3333
Epoch 61/200
15/15 [==============================] - 0s 11ms/step - loss: 2.5643e-06 - accuracy: 1.0000 - val_loss: 11.3062 - val_accuracy: 0.3333
Epoch 62/200
15/15 [==============================] - 0s 16ms/step - loss: 2.4742e-06 - accuracy: 1.0000 - val_loss: 3.0616 - val_accuracy: 0.3333
Epoch 63/200
15/15 [==============================] - 0s 11ms/step - loss: 2.4001e-06 - accuracy: 1.0000 - val_loss:

15/15 [==============================] - 0s 11ms/step - loss: 6.5697e-07 - accuracy: 1.0000 - val_loss: 7.1846 - val_accuracy: 0.3333
Epoch 113/200
15/15 [==============================] - 0s 16ms/step - loss: 6.4638e-07 - accuracy: 1.0000 - val_loss: 7.1933 - val_accuracy: 0.3333
Epoch 114/200
15/15 [==============================] - 0s 11ms/step - loss: 6.4373e-07 - accuracy: 1.0000 - val_loss: 9.4897 - val_accuracy: 0.3333
Epoch 115/200
15/15 [==============================] - 0s 16ms/step - loss: 6.2254e-07 - accuracy: 1.0000 - val_loss: 11.5582 - val_accuracy: 0.3333
Epoch 116/200
15/15 [==============================] - 0s 11ms/step - loss: 6.0929e-07 - accuracy: 1.0000 - val_loss: 2.2931 - val_accuracy: 0.3333
Epoch 117/200
15/15 [==============================] - 0s 10ms/step - loss: 6.0134e-07 - accuracy: 1.0000 - val_loss: 4.5501 - val_accuracy: 0.3333
Epoch 118/200
15/15 [==============================] - 0s 10ms/step - loss: 5.8545e-07 - accuracy: 1.0000 - val_loss: 4.7675 

15/15 [==============================] - 0s 16ms/step - loss: 2.5166e-07 - accuracy: 1.0000 - val_loss: 3.7286 - val_accuracy: 0.3333
Epoch 168/200
15/15 [==============================] - 0s 11ms/step - loss: 2.4901e-07 - accuracy: 1.0000 - val_loss: 3.5422 - val_accuracy: 0.3333
Epoch 169/200
15/15 [==============================] - 0s 10ms/step - loss: 2.4107e-07 - accuracy: 1.0000 - val_loss: 5.2983 - val_accuracy: 0.3333
Epoch 170/200
15/15 [==============================] - 0s 10ms/step - loss: 2.3577e-07 - accuracy: 1.0000 - val_loss: 9.6755 - val_accuracy: 0.3333
Epoch 171/200
15/15 [==============================] - 0s 10ms/step - loss: 2.3047e-07 - accuracy: 1.0000 - val_loss: 5.3040 - val_accuracy: 0.3333
Epoch 172/200
15/15 [==============================] - 0s 10ms/step - loss: 2.2252e-07 - accuracy: 1.0000 - val_loss: 7.5626 - val_accuracy: 0.3333
Epoch 173/200
15/15 [==============================] - 0s 11ms/step - loss: 2.1987e-07 - accuracy: 1.0000 - val_loss: 4.3846 -

In [11]:
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
accuracy: 33.33%


In [13]:

print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'circle': 0, 'rectangle': 1, 'triangle': 2}
[[0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.633 0.001 0.366]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 0.999]
 [0.001 0.001 0.998]
 [0.320 0.000 0.680]
 [0.000 0.000 1.000]
 [0.055 0.000 0.945]
 [0.005 0.000 0.995]
 [0.000 0.000 1.000]
 [0.000 0.006 0.994]]


In [14]:
for i in range(len(test_generator.labels)):
    print(test_generator.filenames[i], test_generator.labels[i], np.argmax(output[i]))

circle\circle021.png 0 2
circle\circle022.png 0 2
circle\circle023.png 0 2
circle\circle024.png 0 2
circle\circle025.png 0 0
rectangle\rectangle021.png 1 2
rectangle\rectangle022.png 1 2
rectangle\rectangle023.png 1 2
rectangle\rectangle024.png 1 2
rectangle\rectangle025.png 1 2
triangle\triangle021.png 2 2
triangle\triangle022.png 2 2
triangle\triangle023.png 2 2
triangle\triangle024.png 2 2
triangle\triangle025.png 2 2
